Repository alexandriawhite/Blue-Ocean, pull requests merged in 2022-12, with the labels that each got.

#62 hobbies appends correctly on profile page
  assets/js/userhobbies.js
  profile.html
Labels: enhancement

#63 Updated matchqueue format and css. updated api to only pull the US.
  assets/css/matches.css
  assets/js/apiscript.js
  assets/js/matches.js
  matchQueue.html
Labels: enhancement

#65 Added videos of functionality to readMe
  README.md
Labels: documentation

#64 comments added to html, js, and css
  assets/css/displayprofile.css
  assets/css/hobbies.css
  assets/css/matches.css
  assets/css/profile.css
  assets/css/style.css
  assets/html/404.html
  assets/js/apiscript.js
  assets/js/displayprofile.js
  assets/js/matches.js
  assets/js/profile.js
  assets/js/queue.js
  assets/js/script.js
  displayprofile.html
  hobbies.html
  index.html
  matchQueue.html
  matches.html
  profile.html
  userhobbies.html
Labels: documentation

#66 I will continue researching the upload image API. I was unsuccessful …
  assets/css/profile.css
  assets/images/heart.PNG
  assets/images/heart.webp
  assets/js/matches.js
  assets/js/profile.js
  assets/js/script.js
  displayprofile.html
Labels: enhancement

#67 removed console.logs
  assets/js/apiscript.js
  assets/js/matches.js
  assets/js/script.js
  assets/js/userhobbies.js
Labels: enhancement

#68 Working on photo for profile and displayprofile HTMLs. Will push afte…
  assets/css/image.css
  assets/css/profile.css
  assets/js/displayprofile.js
  assets/js/image.js
  assets/js/profile.js
  displayprofile.html
  profile.html
Labels: enhancement

#69 Picture is working
  assets/js/displayprofile.js
  assets/js/image.js
  displayprofile.html
  profile.html
Labels: enhancement

#70 Updated photo function. Works if you fill out the full form and save …
  assets/js/image.js
  profile.html
Labels: bug
